### ISSUE TITLE
Error in compiling from source (linux and windows) [ade-xjc-2.6.1]

### ISSUE THREAD

**Issue by vincentsohjh** [citygml4j/ade-xjc#1]
Following the compilation steps provided, I seem to have an error after compilation. This happens for both windows and ubuntu.

When using the run-sample in the sample folder, the following errors occur.

[1:07:57 info] Starting ade-xjc compiler
[1:07:57 info] Setting up build environment
[1:07:57 info] Running in strict mode. Checking sanity of subfolder 'schemas'
[1:07:57 error] Contents of subfolder 'schemas' have been altered. Please restore its original state.
[1:07:57 error] Unable to recover from previous error(s). Aborting.

There is no problem when using the downloaded binaries for windows.

For ubuntu, the following error occurs for the downloaded binaries:
/usr/bin/env: ‘sh\r’: No such file or directory

For ubuntu, the issue is solved with run-sample not starting with "#".

Just to check, for compilation from source, is there any specific environment and settings that was used to generate the binaries for "ade-xjc-2.6.1"?

Thank you.

**Comment by clausnagel** [comment]
I could not reproduce the error under Windows. Could you please apply the following steps:

1. Do a fresh clone of the master branch using `git clone https://github.com/citygml4j/ade-xjc.git`
2. In a DOS window, run `gradlew installDist` in the root of the cloned directory
3. Change directory to the sample in the build directory: `cd build\install\ade-xjc\sample`
4. In that directory, run the sample: `run-sample.bat`

On my machine, the sample runs without errors. I will check under Ubuntu as well. Seems to be a line ending issue...

In general: You can use the `-non-strict` argument to stop ade-xjc from checking the sanity of the schemas folder.

**Comment by clausnagel** [comment]
I tested with Ubuntu and adapted some code lines. Now it should also work properly under Linux. 

For testing, please do a fresh clone again. Note that you most likely will have to make the scripts `gradlew` and `run-sample` executable. Simply use `chmod 755 [filename]` for this purpose.

**Comment by vincentsohjh** [comment]
Hi Claus, thank you! It's working great now. It does not have the problem even though I do not use the `-non-strict` argument.

**Comment by vincentsohjh** [comment]
Hi Claus, thank you! It's working great now. It does not have the problem even though I do not use the -non-strict argument.
